# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
import numpy as np
print(np.zeros((2, 3)), "zeros會初始化數列並塞入0")
print(np.empty((2, 3)), "empty會放入趨近於0的數,但不會初始化數列")

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件

import numpy as np

In [21]:
# 參考解答

a = np.random.rand(2, 3)
b = np.array(a*100, dtype= int)
print(a)
print(b)

[[0.62203539 0.05170265 0.96289419]
 [0.51263869 0.13804363 0.49157644]]
[[62  5 96]
 [51 13 49]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [31]:
m = 20
n = 40

a = np.random.rand(2, 3) * (n - m) # 將範圍限定於(n - m)內
print(a)
b = a
print((a - b % 1) + m) # 以減去小數點的餘數取整數 
                       # 將範圍位移20以達到目標範圍


[[17.29588414 13.01806139  5.44852265]
 [ 3.91687509  9.59246376  9.86180262]]
[[37. 33. 25.]
 [23. 29. 29.]]
