# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
# 記得先 Import 正確的套件
import numpy as np
a = np.arange(1, 12, 1)
num = list(range(3, 7, 1))
b = []
for x in a:
    if x in num:
        b.append(-x)
    else:
        b.append(x)
        
print(b)

[1, 2, -3, -4, -5, -6, 7, 8, 9, 10, 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [2]:
A = np.random.rand(3, 6)
b = []
print(A)
print(A[A>0.5].size)

[[0.09581649 0.88084849 0.87142871 0.02681235 0.22152802 0.50691363]
 [0.4822903  0.10972244 0.59819217 0.12833876 0.78646574 0.07490902]
 [0.42140956 0.55032673 0.71774641 0.75953481 0.04028682 0.60642514]]
9
