# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [5]:
import numpy as np
a = np.arange(10).reshape(2, 5)
print(a)
print(a.sum())
print(np.sum(a))
print(sum(a))

[[0 1 2 3 4]
 [5 6 7 8 9]]
45
45
[ 5  7  9 11 13]


sum()於多維陣列會回傳預設x=0之加總

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [ ]:
# 記得先 Import 正確的套件
import numpy as np

In [8]:
A = np.random.random((5, 5))
print(np.min(A))
print(A.max())
print((A - np.min(A)) / (np.max(A) - np.min(A)) ) 

0.0975630297494624
0.9156700374011723
[[0.01323665 0.84315957 0.12117057 0.64854133 0.92407773]
 [0.05378797 0.2661356  0.57129473 0.9060476  0.        ]
 [0.89600583 0.90531377 0.6493011  0.3988923  0.60794896]
 [0.8234856  0.06035687 0.88611113 0.87295224 1.        ]
 [0.41162913 0.46525315 0.93100984 0.85018731 0.41490291]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [11]:
a = np.random.randint(0, 100, 10)
print(a)
print(a.argmax())
a[a.argmax()] = -1
print(a)

[93  5 41 43 36 64 40  2 65 39]
0
[-1  5 41 43 36 64 40  2 65 39]
