# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [2]:
# 記得先 Import 正確的套件

import numpy as np

In [3]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [4]:
%timeit -n 10 a = 2
for i in Z:
    i = i +1

38.6 ns ± 13.6 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit -n 10 a = 2

Z = Z+1

The slowest run took 56.33 times longer than the fastest. This could mean that an intermediate result is being cached.
273 ns ± 579 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
%timeit -n 10 a = 2
for x in Z.flat:
    x += 1

103 ns ± 16.7 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%timeit -n 10 a = 2
for z in np.nditer(Z, op_flags=['readwrite']):
    z += 1

35.7 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [8]:

Z = np.random.randint(0,10,50)
print(Z)


[0 2 6 2 5 8 0 4 6 7 6 8 7 9 9 2 6 0 4 7 8 3 8 9 1 9 2 9 6 1 3 7 7 8 6 2 5
 0 6 7 8 6 5 9 1 9 4 1 8 1]


In [9]:
values, counts = np.unique(Z, return_counts=True)
print(values, '\n',counts)

int = values[counts.argmax()]
print("出現頻率最高為", int)

freq = counts.max()
print("頻率最高為",freq, "次")

[0 1 2 3 4 5 6 7 8 9] 
 [4 5 5 2 3 3 8 6 7 7]
出現頻率最高為 6
頻率最高為 8 次


In [10]:
rint = (np.bincount(Z).argmax())
print(rint)
print(np.where(Z == rint)[0])

6
[ 2  8 10 16 28 34 38 41]


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [21]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))



[9, 5, 1, 1, 6, 7]
[9, 5, 1, 1, 6, 7]
[[9, 0, 8, 4], [4, 6, 8, 3], [4, 5, 1, 9]]
[array([9, 0, 8, 4]), array([4, 6, 8, 3]), array([4, 5, 1, 9])]
[[[7, 7], [0, 2], [9, 0]], [[0, 8], [8, 3], [6, 8]]]
[array([[7, 7],
       [0, 2],
       [9, 0]]), array([[0, 8],
       [8, 3],
       [6, 8]])]
[1, 2, 3, 4]
['a', 'b']


In [22]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return tolist(newlist)
print(tolist(a))

print(tolist(b))

print(tolist(c))

[9, 5, 1, 1, 6, 7]
[[9, 0, 8, 4], [4, 6, 8, 3], [4, 5, 1, 9]]
[[[7, 7], [0, 2], [9, 0]], [[0, 8], [8, 3], [6, 8]]]
['a', 'b']


In [25]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]
print(tolist(a))

print(tolist(b))

print(tolist(c))

[9, 5, 1, 1, 6, 7]
[[9, 0, 8, 4], [4, 6, 8, 3], [4, 5, 1, 9]]
[[[7, 7], [0, 2], [9, 0]], [[0, 8], [8, 3], [6, 8]]]
