# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [18]:
import numpy as np
a = np.random.randint(2, size= (3, 5))
print(a)
print("========")
print("list(a):", list(a))
print("========")
print("tolist:", a.tolist())
print("========")
print("list僅轉換第一層: 3x5 -> 1x5","\n","a.tolist()可進行多層轉換")

[[1 0 1 1 0]
 [1 0 1 0 1]
 [0 0 0 0 1]]
list(a): [array([1, 0, 1, 1, 0]), array([1, 0, 1, 0, 1]), array([0, 0, 0, 0, 1])]
tolist: [[1, 0, 1, 1, 0], [1, 0, 1, 0, 1], [0, 0, 0, 0, 1]]
list僅轉換第一層: 3x5 -> 1x5 
 a.tolist()可進行多層轉換


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [36]:
a = np.random.randint(10, size=6) 
print(a)
print("幾個維度:",a.ndim)
print("陣列形狀:",a.shape)
print("資料數量:",a.size)
print("資料型態:",a.dtype)
print("每元素佔的位元組:",a.itemsize)
print("第一層資料數量:",len(a))
print("陣列類別:",type(a))

[9 7 4 0 0 7]
幾個維度: 1
陣列形狀: (6,)
資料數量: 6
資料型態: int32
每元素佔的位元組: 4
第一層資料數量: 6
陣列類別: <class 'numpy.ndarray'>


In [37]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print("幾個維度:",b.ndim)
print("陣列形狀:",b.shape)
print("資料數量:",b.size)
print("資料型態:",b.dtype)
print("每元素佔的位元組:",b.itemsize)
print("第一層資料數量:",len(b))
print("陣列類別:",type(b))

[[8 9 8 3]
 [2 8 0 3]
 [6 5 6 5]]
幾個維度: 2
陣列形狀: (3, 4)
資料數量: 12
資料型態: int32
每元素佔的位元組: 4
第一層資料數量: 3
陣列類別: <class 'numpy.ndarray'>


In [38]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print("幾個維度:",c.ndim)
print("陣列形狀:",c.shape)
print("資料數量:",c.size)
print("資料型態:",c.dtype)
print("每元素佔的位元組:",c.itemsize)
print("第一層資料數量:",len(c))
print("陣列類別:",type(c))

[[[9 8]
  [0 2]
  [1 5]]

 [[6 3]
  [8 3]
  [6 8]]]
幾個維度: 3
陣列形狀: (2, 3, 2)
資料數量: 12
資料型態: int32
每元素佔的位元組: 4
第一層資料數量: 2
陣列類別: <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [43]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[9, 1, 9, 9, 0, 5]
[9, 1, 9, 9, 0, 5]


In [44]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[1, 9, 3, 7], [9, 9, 4, 9], [7, 9, 0, 9]]
[array([1, 9, 3, 7]), array([9, 9, 4, 9]), array([7, 9, 0, 9])]


In [45]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 5], [8, 9], [3, 5]], [[2, 9], [7, 3], [1, 5]]]
[array([[0, 5],
       [8, 9],
       [3, 5]]), array([[2, 9],
       [7, 3],
       [1, 5]])]


In [46]:
def tolist(iterable):
    result= iterable.tolist()
    return result

print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 1, 9, 9, 0, 5]
[[1, 9, 3, 7], [9, 9, 4, 9], [7, 9, 0, 9]]
[[[0, 5], [8, 9], [3, 5]], [[2, 9], [7, 3], [1, 5]]]
